# Copyright 2021 Przemysław Lal
# See LICENSE file for licensing details.

options:
  span-storage-type:
    default: elasticsearch
    description: |
      Storage backend.
      Supported options:
        - elasticsearch
    type: string
  agent-port:
    default: 6831
    description: |
      Port that the agent will use to listen on jaeger.thrift over compact Thrift protocol.
    type: int
  agent-port-binary:
    default: 6832
    description: |
      Port that the agent will use to listen on jaeger.thrift over binary Thrift protocol.
    type: int
